version: 2

project_name: krnr

builds:
  - id: krnr
    binary: krnr
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/VoxDroid/krnr/internal/version.Version={{.Version}}

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
  - format: zip
    goos: [windows]
    files:
      - LICENSE
      - README.md

nfpms:
  - path: packaging/nfpm/deb.yml
  - path: packaging/nfpm/rpm.yml

brews:
  - name: krnr
    repo: VoxDroid/homebrew
    commit_author:
      name: "VoxDroid"
      email: "izeno.contact@gmail.com"

snapshot:
  name_template: 'krnr-{{ .Version }}'

release:
  github:
    owner: VoxDroid
    name: krnr

changelog:
  use: git
