version: 2

project_name: krnr

builds:
  - id: krnr
    binary: krnr
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/VoxDroid/krnr/internal/version.Version={{.Version}}

archives:
  - id: default
    builds: [krnr]
    format: tar.gz
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: krnr
    package_name: krnr
    builds: [krnr]
    vendor: VoxDroid
    homepage: https://github.com/VoxDroid/krnr
    maintainer: VoxDroid <izeno.contact@gmail.com>
    description: Kernel-related CLI utility
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

# brews:
#   - name: krnr
#     repository:
#       owner: VoxDroid
#       name: homebrew
#     homepage: https://github.com/VoxDroid/krnr
#     description: Kernel-related CLI utility
#     commit_author:
#       name: VoxDroid
#       email: izeno.contact@gmail.com

snapshot:
  name_template: "krnr-{{ .Version }}"

release:
  github:
    owner: VoxDroid
    name: krnr

changelog:
  use: git
